# Generated by Django 4.0.2 on 2022-03-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='newapp.PostCategory', to='newapp.Category'),
        ),
    ]
