# Generated by Django 4.0.2 on 2022-04-16 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newapp', '0002_alter_post_postcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subs',
            field=models.ManyToManyField(through='newapp.SubsUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsuser',
            name='subsThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.category'),
        ),
        migrations.AddField(
            model_name='subsuser',
            name='userThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
